### ISSUE TITLE
Local news reporting based on user location

### ISSUE THREAD

**Issue by code247** [tripleblindmarket/covid-safe-paths#156]

**Comment by E3V3A** [comment]
Great idea, but how to source what is local? Can you come up with any ideas on how we can go about to implement this?

**Comment by penrods** [comment]
This is coming with the addition of subscribed Health Authorities in Safe Paths.  That will define what is "local" to you!

**Comment by E3V3A** [comment]
> This is coming with the addition of subscribed Health Authorities in Safe Paths. That will define what is "local" to you!

Who's gonna wet that? I can assure you there are a lot of poor *news* sources in countries that doesn't have multinational news outlets. So it's essential to understand how you're sourcing those? 

It would also be great if we did not have to watch and maintain several different repositories in order to know what sources that might be. Is there a way to  make this one a little more self contained? At least regarding the functional information flow? 

> This is coming with the addition of subscribed Health Authorities in Safe Paths.

I mean, do we really need to cross-post the question to the "Safe Paths" repo and start digging in that, in order to get simple answers, such as how the "news" engine is fed?

**Comment by diarmidmackenzie** [comment]
As we look to going live, I think it's urgent that we fix this.

Not essential that we actually link to local news sources, but the current screen showing a Mock-up with the Haitinan Ministry of test is unacceptable for launch IMO.

Better to have a banner that says "coming soon" on this page.

**Comment by penrods** [comment]
Each Health Authority self-declares its News source.  You don't have to subscribe to it, hence the phrase "trusted Health Authority".

When you say "we don't have to watch" do you me you as an individual?  Or "we" as in this project?  Individuals don't care about repos at all, it just shows up on their phone as an option.

**Comment by penrods** [comment]
#499 removes the Haiti news from the default.

**Comment by penrods** [comment]
I think this is resolved, so I'm going to close this issue out.
