### ISSUE TITLE
UX - Public Data is Confusing

### ISSUE THREAD

**Issue by DavidMershon81** [tripleblindmarket/covid-safe-paths#339]
As an end user, it's not clear to me what I'm seeing on the public data screen. It says "The light purple circles represent the public dataset". What does that mean? 
- Does a purple circle represent someone with COVID-19 who has been running the app has been in the circled region?
- How does an end user use this information to help contain the virus? It's not obvious what steps I should take if I find myself within one of those circles.
- The "For more information on the dataset for this  map" button does not lead to anything that is in any way user friendly enough for the general public to understand. I am a software engineer I still don't understand what I am supposed to make of the site this button linked to.

![private kit public data](https://user-images.githubusercontent.com/63134933/78417304-91a9b400-75e5-11ea-830c-954e8ec1a252.PNG)

**Comment by kenpugsley** [comment]
This will be addressed after the v1.0 release.  This functionality is being removed from the product for now because of the confusion it causes.  We will revisit this functionality in the following release.

Leaving this open for now as it is something to address.

**Comment by E3V3A** [comment]
@kenpugsley 
Why not just describe the intended function and behavior right now? (What do you want to wait for exactly?) Because by the time *next release* happens, there will be at least another mother load of dead people. And as an *end user*, not showing anything, is certainly not going to make this app more attractive. At minimum, at least point the developers to the right documentation for this, if there is any.

**Comment by penrods** [comment]
No longer part of Safe Paths.
