### ISSUE TITLE
Reduce payload by 3.5% by eliminating milliseconds

### ISSUE THREAD

**Issue by dashroad** [tripleblindmarket/covid-safe-paths#350]
{
        "latitude": 25.3121075,
        "longitude": 55.4980093,
        "time": 1585340646216

Remove last 3 digits of time, to eliminate milliseconds and stay with seconds.

**Comment by denispapakul** [comment]
So, where it should be done?
Cause now in the app, I see  time in ms with last 3 digits - 0, for example - 1585340646000
Actually milliseconds - it's default sets for time

**Comment by kenpugsley** [comment]
Need to be careful on this ... changing the time format will have impact on the Safe Places app.  Any change would need to be coordinated with that project.

**Comment by ten-sis** [comment]
@dashroad, could you please elaborate what exactly payload are you talking about?

Moving away from milliseconds might cause an unnecessary headache as multiple things depend on time to be in milliseconds, e.g. [Date constructor in JS expects milliseconds](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date), google takeout archive supplied to Import feater also uses milliseconds. 

I'd suggest to defer any payload optimization until there is any real related performance issue on a horizon.

**Comment by dashroad** [comment]
I'm not familiar w/ the JS constructor, but I would suggest to leave it as you said, an option for optimization if/when the time comes.

**Comment by E3V3A** [comment]
Experience tell me...that time will never come. Do it now, or don't do it at all.

**Comment by diarmidmackenzie** [comment]
See https://github.com/tripleblindmarket/covid-safe-paths/issues/325 for some evidence that we do have issues with the size of data.

In addition to moving to seconds, we could make some other changes to the data format without losing much:

"time" -> "t"
"longitude"-> "x"
"latitude" -> "y"
GPS data to 5 decimal points, rather than 8.  (gives 10m accuracy, below that data is probably spuriously accurate anyway).

That adds up to a 31% gain - a bit more than the original 3.5%.

If you want to keep 6 DP of GPS data, rather than 5 (1m accuracy rather than 10m), you can achieve a 29% reduction.

**Comment by penrods** [comment]
Eliminating "ms" or a few decimal places is not the best way to compress data.  Going to a binary format does that -- 3 floats would be 4 bytes * 3 = 12 bytes per entry.  That's basically the cost of the json formating characters for each entry: {"": , "":, "": }

**Comment by summetj** [comment]
Closing this suggestion, if data storage size becomes an issue in the future, need to coordinate with safe places webapp and consider binary format.
