### ISSUE TITLE
Determine the correct scheme to backfill points (LocationService)

### ISSUE THREAD

**Issue by kenpugsley** [tripleblindmarket/covid-safe-paths#394]
#389 introduces a limit on the amount of time we will try to backfill.  Filing this issue to come back to that logic and be backfill and make sure we're doing the best we can do.

**Comment by JohnPalmer** [comment]
I suggest that if we use backfilling, we mark the locations that are added this way so that analysts can distinguish them from the observed locations. This would mean adding a new key to the json file and thus increasing the size, but I worry that we may be distorting the data otherwise and making it impossible for someone to later fix it. For example, we may later realize that there is a better approach to dealing with gaps (this is something that I work on) that we would like to implement in the app and/or in the Safe Places tool for public health authorities analyzing the data. If we do not have the backfilled locations marked, we (or they) will not be able to do anything to apply the alternative approach to already-gathered data.

**Comment by kenpugsley** [comment]
Thanks @JohnPalmer  - that's a great idea.  We're also looking at if the backfill is truly necessary.  The main reason we do it is to cover the case where we don't get location updates from the device because it is not moving.  It's unclear if this is actually an issue.  I think you're comments above might also be helpful in letting us know if this is indeed something we need to do.

**Comment by JohnPalmer** [comment]
Thanks @kenpugsley. This also connects to #403, which I just commented on as well. Since this is something I spent a lot of time thinking through a few years ago, I will focus on it more now.

**Comment by penrods** [comment]
Addressed now.   Closing.
