### ISSUE TITLE
FEATURE: Verify application freshness

### ISSUE THREAD

**Issue by penrods** [tripleblindmarket/covid-safe-paths#40]
Add a mechanism to remind the user to update if they have turned off auto-updates on their phone.

The first version can be a simple notification when the app is outdated.

**Comment by tushar-dadlani** [comment]
A library that can be used. I'm new to react native, I'll try this out

Do we have CI to test iOS and android? 

https://github.com/kimxogus/react-native-version-check

**Comment by harshvitra** [comment]
@tushar-dadlani  

Hey did you get to try the library ? 
The functions are capable of achieving what we need

**Comment by snmishra** [comment]
I've used [codepush](https://github.com/Microsoft/react-native-code-push) in one of my previous apps. It's a heavier change requiring changes to the release process. But it does allow updating the javascript bundle without updating the entire app. It turned out to be less useful in the initial releases where the native code was also changing fast. Still, I was able to fix some crashes quickly without having to wait for the user to update the app.
