### ISSUE TITLE
Settings does not show on iOS 12.0

### ISSUE THREAD

**Issue by kenpugsley** [tripleblindmarket/covid-safe-paths#528]
The settings icon / action does not show on the LocationTracking screen in iOS 12.0 (only the 12.0.x versions, all other versions seem to be OK)

COVID Safe Paths v0.9.2 (probably earlier, probably later as well)

- Type of phone: iPhone
- OS Version: 12.0
- Model: all models

## Steps to reproduce

On macOS with recent xcode installed you can get this to happen in the simulator.  `npx react-native run-ios --simulator "iPhone 5s (12.0)"`

![Simulator Screen Shot - iPhone 7 - 2020-04-15 at 03 34 37](https://user-images.githubusercontent.com/4031514/79398763-07e3da00-7f47-11ea-8c2f-cc67f3dbd33b.png)

**Comment by Krish023** [comment]
I can look into this issue. Please assign it to me.

**Comment by Krish023** [comment]
Hi,

I have checked on iPhone 8 with ios 12.1. But I can see the settings button. Could you please specify the iPhone model with the 
<img width="559" alt="Screenshot 2020-04-16 at 10 37 51 AM" src="https://user-images.githubusercontent.com/503055/79416899-699b5700-7fce-11ea-857d-2a667fe73615.png">
OS version.

Thanks,
Krishna

**Comment by tremblerz** [comment]
It only fails with the ios 12.0 apparently

**Comment by Krish023** [comment]
Thanks @tremblerz I will look at it.

**Comment by Krish023** [comment]
Hi @tremblerz, It's the issue with the Library (react-native-svg). We can do an action but image is not visible. I have tried with image data and working fine. Should we use Image data instead of svg?
<img width="556" alt="Screenshot 2020-04-20 at 11 23 18 AM" src="https://user-images.githubusercontent.com/503055/79719226-b9925a80-82fb-11ea-8450-56f5bccf4a05.png">
<img width="556" alt="Screenshot 2020-04-20 at 11 23 21 AM" src="https://user-images.githubusercontent.com/503055/79719230-bbf4b480-82fb-11ea-8f64-515d3539df63.png">
