### ISSUE TITLE
Import Locations from Google on iOS: Browser opens the Zip file in the Webview. 

### ISSUE THREAD

**Issue by vitorpamplona** [tripleblindmarket/covid-safe-paths#77]
On Android, the app saves a file in the Downloads folder. 

On iOS, the WebView shows the zipped binary file in the app itself. 

We need to figure out a way to either download it to a file and then open with the SearchAndImport function or keep it in memory (500MB in memory?) and pass it to the SearchAndImport function.

**Comment by 1geek0** [comment]
How large can the location history file get?

**Comment by vitorpamplona** [comment]
My 7 years are 500MB :(

**Comment by 1geek0** [comment]
Do we need that much? Can we add a date range to it?

**Comment by remintz** [comment]
Just to illustrate what happens on IOS after downloading...
![IMG_903E13968C76-1](https://user-images.githubusercontent.com/4155238/77321194-95d5f780-6cf0-11ea-87a1-b57e95cb8df8.jpeg)

**Comment by sergesemashko** [comment]
#69 is related to this issue, also there is WIP PR [#282 Change Import from webview to file picker](https://github.com/tripleblindmarket/covid-safe-paths/pull/282) that removes embedded webview for improved experience/privacy. 

If it was up to me, I'd prefer to keep an approach from PR [#282](https://github.com/tripleblindmarket/covid-safe-paths/pull/282) that user has to login into google account rather from browser instead of webview and being able to select file from downloads folder. 
 
So, this issue might no longer be relevant if the core and product team decides to favor the approach from #69 issue.

**Comment by popofibo** [comment]
I kind of agree to replace webview with a file picker but unsure what is the timeline for that merge to happen.  It's a cleaner approach no doubt but I personally did not get a chance to test it; this maybe a stopgap to alleviate the current broken iOS experience.

**Comment by tremblerz** [comment]
I was working on #282 to fix, it still doesn't work but it would be great if someone is willing to lend a hand, it is a very high priority https://github.com/tripleblindmarket/covid-safe-paths/pull/282

**Comment by sergesemashko** [comment]
By the way, the solution for large takeout files might be unzipping somewhere else and import only json files for the latest months manually into the app, e.g. `2020_APRIL.json`. The can be attached.

Under the hood, we can be checking the location timestamp freshness and let's say include only locations for the past 30 days.
