### ISSUE TITLE
The location settings alert box is not consistent

### ISSUE THREAD

**Issue by tremblerz** [tripleblindmarket/covid-safe-paths#84]
Right now for the phone versions which don't show 3 options for location (while using, always, never) but instead 2 options (always/yes, never), the location prompts up for them unnecessarily. We will have to dig deep into the response numbers by the geolocation api.

**Comment by skusunam** [comment]
@tremblerz Is this bug on iOS or Android? I see 3 options on the iOS 11 emulator?

**Comment by tremblerz** [comment]
@skusunam yes there are quite a few alert boxes when user starts the app on  both platforms

**Comment by sergesemashko** [comment]
@tremblerz, Could you please elaborate what is the expected behavior and specify platform (IOS | Android and version)? 

I can see the system prompt asking for location permission, but not sure I understand the expected behavior.
![Screen Shot 2020-04-05 at 7 10 43 PM](https://user-images.githubusercontent.com/1267571/78512432-656f6e00-7772-11ea-9a29-6c9a050c13b4.png).

**Comment by harshvitra** [comment]
@tremblerz can we have a list of expected behaviour for this
